# Generated by Django 5.0.7 on 2024-07-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='schoollist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=14, unique=True)),
                ('address', models.CharField(max_length=30)),
            ],
        ),
    ]
